spring.application.name=feita_debronze

# --- Configuração do Banco de Dados MySQL ---
# A opção 'createDatabaseIfNotExist=true' cria o banco 'db_bronze' se ele não existir.
# 'allowPublicKeyRetrieval=true' é adicionado para resolver o erro "Public Key Retrieval is not allowed".
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# --- Configuração do JPA (Hibernate) ---
# 'update': Cria as tabelas se não existirem e atualiza o esquema se houver alterações nas entidades.
# Use 'create' se quiser apagar e recriar o banco toda vez que iniciar a aplicação (cuidado com dados em produção).
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# --- Configuração do Servidor ---
server.port=8080

