spring.application.name=feita_debronze

# Configuração para PostgreSQL na Render
spring.datasource.url=jdbc:postgresql://://dpg-d6d5bhh4tr6s73cjov90-a.oregon-postgres.render.com
spring.datasource.username=root
spring.datasource.password=6yM4tOq16fmo3c7N0aZtS0n6SVlG5Qfu

# O segredo para criar as tabelas automaticamente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true



# --- ConfiguraÃ§Ã£o do Servidor ---
server.port=8080

